---
title: "Lectures"
---

## Lecture Slides

Lecture slides are available as self-contained `.html` files made with RevealJS from a Quarto `.qmd` file. You can choose to print these to a PDF document by using the "PDF Export Mode" in the Tools menu accessed via the settings button in the lower left-hand side of the page. You are also welcome to directly download the `.qmd` file and supporting data/images/etc... from the Github repository. Slides are organized by week and combine Monday and Wednesday's lectures.

### Week 1: Statistical Review

- [Week 1 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week1/)
- [Week 1 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week1/week1_intro_and_review.html)

### Week 2: Potential Outcomes + Randomized Experiments

- [Week 2 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week2/)
- [Week 2 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week2/week2_potential_outcomes_and_experiments.html)

### Week 3: Experiments: Attrition and Generalizability 

- [Week 3 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week3/)
- [Week 3 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week3/week3_experiments_part_2.html)

### Week 4: Experiments: Incorporating Covariates

- [Week 4 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week4/)
- [Week 4 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week4/week4_experiments_covariate_adjustment.html)

### Week 5: Selection-on-Observables

- [Week 5 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week5/)
- [Week 5 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week5/week5_observational_designs.html)

### Week 6: Selection-on-Observables - Regression and Weighting

- [Week 6 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week6/)
- [Week 6 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week6/week6_regression_and_weighting.html)

### Week 7: Selection-on-Observables - Matching

- [Week 7 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week7/)
- [Week 7 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week7/week7_matching.html)

### Week 8: Instrumental Variables

- [Week 8 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week8/)
- [Week 8 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week8/week8_instrumental_variables.html)

### Week 9: Differences-in-Differences

- [Week 9 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week9/)
- [Week 9 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week9/week9_differences_in_differences.html)

### Week 10: Modern Differences-in-Differences

- [Week 10 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week10/)
- [Week 10 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week10/week10_modern_differences_in_differences.html)

### Week 11: Panel Data Causal Inference

- [Week 11 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week11/)
- [Week 11 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week11/week11_panel_data_causal_inference.html)

### Week 12: Regression Discontinuity Designs

- [Week 12 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week12/)
- [Week 12 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week12/week12_regression_discontinuity.html)

### Week 13 Part 1: Mediation

- [Week 13 Part 1 Github Repository](https://github.com/astrezhnev/ps813/tree/main/slides/week13/part1/)
- [Week 13 Part 1 `.html` slides](https://www.antonstrezhnev.com/ps813/slides/week13/part1/week13_mediation.html)

### Week 13 Part 2: Sensitivity Analysis

- Week 13 Part 2 Github Repository
- Week 13 Part 2 `.html` slides

### Week 14: Shift-share Designs and Experiments with Interference

- Week 14 Github Repository
- Week 14 `.html` slides
